networks:
  proxy-net:
    external: true
    name: proxy-net

services:
  portfolio-app:
    build:
      context: .
      args:
        REACT_APP_EMAILJS_SERVICE_ID: ${REACT_APP_EMAILJS_SERVICE_ID}
        REACT_APP_EMAILJS_TEMPLATE_ID: ${REACT_APP_EMAILJS_TEMPLATE_ID}
        REACT_APP_EMAILJS_PUBLIC_KEY: ${REACT_APP_EMAILJS_PUBLIC_KEY}
    restart: unless-stopped
    networks:
      - proxy-net

  portfolio-api:
    build: ./portfolio-api
    restart: unless-stopped
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - proxy-net
