networks:
  proxy-net:
    external: true
    name: proxy-net

services:
  portfolio-app:
    build: .
    restart: unless-stopped
    networks:
      - proxy-net

  portfolio-api:
    build: ./portfolio-api
    restart: unless-stopped
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - proxy-net
